apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # These values should be base64 encoded in a real deployment
  JWT_SECRET: cmVwbGFjZS13aXRoLXlvdXItc2VjcmV0
  STRIPE_API_KEY: eW91ci1zdHJpcGUtYXBpLWtleQ==
  EMAIL_PASSWORD: eW91ci1lbWFpbC1wYXNzd29yZA==
  SMS_API_KEY: eW91ci1zbXMtYXBpLWtleQ== 