apiVersion: v1
kind: Service
metadata:
  name: customer-portal
spec:
  selector:
    app: customer-portal
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-portal
spec:
  selector:
    app: restaurant-portal
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: admin-portal
spec:
  selector:
    app: admin-portal
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
