apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  STRIPE_PUBLISHABLE_KEY_RENAMED: "pk_test_51RFf3eHFMT8polCBCD0rhz3KxeYbxrFscZnSIt1U8uW0DCDvDduGuUhzp8wK3b4z77F9NZcr9rUY3VBjDes1XMkx00GQZ5f5dp"
