apiVersion: v1
kind: ConfigMap
metadata:
  name: service-configs
data:
  # MongoDB URI (this should be in a secret in production)
  MONGODB_URI: "mongodb+srv://cravecartlk:cravecart123@cluster0.8qk0a8n.mongodb.net/cravecart"
  
  # Service names and ports
  SERVICE_NAME_USER: "user-service"
  SERVICE_NAME_RESTAURANT: "restaurant-service"
  SERVICE_NAME_ORDER: "order-service"
  SERVICE_NAME_PAYMENT: "payment-service"
  SERVICE_NAME_DELIVERY: "delivery-service"
  SERVICE_NAME_NOTIFICATION: "notification-service"
  
  # Ports
  PORT_USER: "3001"
  PORT_RESTAURANT: "5004"
  PORT_ORDER: "5003"
  PORT_PAYMENT: "5002" 
  PORT_DELIVERY: "3005"
  PORT_NOTIFICATION: "5005"
