apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-portal
  template:
    metadata:
      labels:
        app: customer-portal
    spec:
      containers:
      - name: customer-portal
        image: cravecart/customer-portal:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        envFrom:
        - configMapRef:
            name: frontend-configs
        - configMapRef:
            name: service-urls
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
