apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-portal-config
  namespace: cravecart
data:
  REACT_APP_API_BASE_URL: "http://34.132.7.64:3001"
  REACT_APP_ORDER_SERVICE_URL: "http://34.45.142.152:5003"
  REACT_APP_NAME: "Admin Portal"
  REACT_APP_VERSION: "1.0.0"
  PORT: "3003"
  REACT_APP_USER_SERVICE_URL: "http://34.132.7.64:3001"
  REACT_APP_NOTIFICATION_SERVICE_URL: "http://34.58.115.37:5005"
  REACT_APP_RESTAURANT_SERVICE_URL: "http://34.133.20.229:5004"
  REACT_APP_PAYMENT_SERVICE_URL: "http://34.121.113.108:5002"
  REACT_APP_DELIVERY_SERVICE_URL: "http://35.226.92.191:3005"
  REACT_APP_ENV: "production" 
  REACT_APP_ADMIN_WEB_URL: "http://130.211.196.201"
  REACT_APP_CUSTOMER_WEB_URL: "http://35.226.62.115"
  REACT_APP_RESTAURANT_WEB_URL: "http://34.134.98.231"
