apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-service-config
  namespace: cravecart
  
data:
  PORT: "3005"
  SERVICE_NAME: "delivery-service"
  JWT_EXPIRATION: "7d"
  MONGODB_URI: "mongodb+srv://cravecartlk:cravecart123@cluster0.8qk0a8n.mongodb.net/cravecart"
  JWT_SECRET: "cravecart_jwt_secret_key"
  
  # Service URLs
  ORDER_SERVICE_URL: "http://34.49.43.70:5003"
  RESTAURANT_SERVICE_URL: "http://34.111.17.63:5004"
  NOTIFICATION_SERVICE_URL: "http://34.120.18.225:5005"
  DELIVERY_SERVICE_URL: "http://34.110.175.144:3005"
  PAYMENT_SERVICE_URL: "http://34.102.186.211:5002"
  USER_SERVICE_URL: "http://34.8.57.185:3001"
  
  # Web URLs
  CUSTOMER_WEB_URL: "https://customer.cravecart.com"
  ADMIN_WEB_URL: "https://admin.cravecart.com"
  RESTAURANT_WEB_URL: "https://restaurant.cravecart.com"
  
  # Mobile URLs
