apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-service-config
data:
  PORT: "3005"
  NODE_ENV: "production"
  MONGODB_URI: "mongodb+srv://cravecartlk:cravecart123@cluster0.8qk0a8n.mongodb.net/cravecart-delivery"
  ORDER_SERVICE_URL: "http://order-service:5003"
  MAPS_API_KEY: "your-maps-api-key"
  LOG_LEVEL: "info" 