apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  PORT: "5003"
  NODE_ENV: "production"
  MONGODB_URI: "mongodb+srv://cravecartlk:cravecart123@cluster0.8qk0a8n.mongodb.net/cravecart-orders"
  USER_SERVICE_URL: "http://user-service:3001"
  RESTAURANT_SERVICE_URL: "http://restaurant-service:5004"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5005"
  LOG_LEVEL: "info" 