apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  PORT: "3001"
  NODE_ENV: "production"
  MONGODB_URI: "mongodb+srv://cravecartlk:cravecart123@cluster0.8qk0a8n.mongodb.net/cravecart-users"
  JWT_SECRET: "replace-with-your-secret"
  JWT_EXPIRATION: "24h"
  LOG_LEVEL: "info" 