apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: cravecart
 
data:
  PORT: "3001"
  SERVICE_NAME: "user-service"
  JWT_EXPIRATION: "7d"
  MONGODB_URI: "mongodb+srv://cravecartlk:cravecart123@cluster0.8qk0a8n.mongodb.net/cravecart"
  JWT_SECRET: "cravecart_jwt_secret_key"
  
  # Service URLs
  ORDER_SERVICE_URL: "http://34.45.142.152:5003"
  RESTAURANT_SERVICE_URL: "http://34.133.20.229:5004"
  NOTIFICATION_SERVICE_URL: "http://34.58.115.37:5005"
  DELIVERY_SERVICE_URL: "http://35.226.92.191:3005"
  PAYMENT_SERVICE_URL: "http://34.121.113.108:5002"
  USER_SERVICE_URL: "http://34.132.7.64:3001"
  
  # Web URLs
  CUSTOMER_WEB_URL: "http://35.226.62.115"
  ADMIN_WEB_URL: "http://130.211.196.201"
  RESTAURANT_WEB_URL: "http://34.134.98.231"
  
  # Mobile URLs
