apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-portal
  namespace: cravecart
  labels:
    app: admin-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-portal
  template:
    metadata:
      labels:
        app: admin-portal
    spec:
      containers:
      - name: admin-portal
        image: gcr.io/cravecart-web-458310/admin-portal:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1.0"
            memory: "2048Mi"
          requests:
            cpu: "1.0"
            memory: "2048Mi"
        envFrom:
        - configMapRef:
            name: admin-portal-config
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: admin-portal
  namespace: cravecart
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: admin-portal 
