apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-portal
  namespace: cravecartweb
  labels:
    app: customer-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-portal
  template:
    metadata:
      labels:
        app: customer-portal
    spec:
      containers:
      - name: customer-portal
        image: gcr.io/cravecart-web-458310/customer-portal:v-20250502002903
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: customer-portal
  namespace: cravecartweb
spec:
  selector:
    app: customer-portal
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
