apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: cravecart
  
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      volumes:
      - name: src-volume
        configMap:
          name: notification-service-src
      containers:
      - name: notification-service
        image: gcr.io/cravecart-457103/notification-service:latest
        ports:
        - containerPort: 5005
        volumeMounts:
        - name: src-volume
          mountPath: /usr/src/app/src/server.js
          subPath: server.js
        resources:
          limits:
            cpu: "1.0"
            memory: "2048Mi"
          requests:
            cpu: "1.0"
            memory: "2048Mi"
        envFrom:
        - configMapRef:
            name: notification-service-config
        readinessProbe:
          httpGet:
            path: /health
            port: 5005
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5005
          initialDelaySeconds: 30
