apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cravecart

  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: gcr.io/cravecart-457103/order-service:latest
        ports:
        - containerPort: 5003
        resources:
          limits:
            cpu: "0.5"
            memory: "1024Mi"
          requests:
            cpu: "0.3"
            memory: "512Mi"
        envFrom:
        - configMapRef:
            name: order-service-config
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5003
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5003
          initialDelaySeconds: 30
