apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: cravecart
  
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: gcr.io/cravecart-457103/payment-service:latest
        ports:
        - containerPort: 5002
        resources:
          limits:
            cpu: "1.0"
            memory: "2048Mi"
          requests:
            cpu: "1.0"
            memory: "2048Mi"
        envFrom:
        - configMapRef:
            name: payment-service-config
        readinessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 30
