apiVersion: v1
kind: Service
metadata:
  name: delivery-service

  labels:
    app: delivery-service
  annotations:
    cloud.google.com/load-balancer-ip: "34.110.175.144"
spec:
  selector:
    app: delivery-service
  ports:
  - port: 3005
    targetPort: 3005
    name: http
