apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  
  labels:
    app: delivery-service
  annotations:
    cloud.google.com/load-balancer-ip: "35.226.92.191"
spec:
  type: LoadBalancer
  loadBalancerIP: "35.226.92.191"
  selector:
    app: delivery-service
  ports:
  - port: 3005
    targetPort: 3005
    name: http
