apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  labels:
    app: delivery-service
spec:
  selector:
    app: delivery-service
  ports:
  - port: 3005
    targetPort: 3005
  type: ClusterIP 