apiVersion: v1
kind: Service
metadata:
  name: notification-service

  labels:
    app: notification-service
  annotations:
    cloud.google.com/load-balancer-ip: "34.120.18.225"
spec:
  selector:
    app: notification-service
  ports:
  - port: 5005
    targetPort: 5005
    name: http
