apiVersion: v1
kind: Service
metadata:
  name: payment-service

  labels:
    app: payment-service
  annotations:
    cloud.google.com/load-balancer-ip: "34.102.186.211"
spec:
  selector:
    app: payment-service
  ports:
  - port: 5002
    targetPort: 5002
    name: http
