apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: cravecart
  
  labels:
    app: payment-service
  annotations:
    cloud.google.com/load-balancer-ip: "34.121.113.108"
spec:
  type: LoadBalancer
  loadBalancerIP: "34.121.113.108"
  selector:
    app: payment-service
  ports:
  - port: 5002
    targetPort: 5002
    name: http
