apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  labels:
    app: restaurant-service
spec:
  selector:
    app: restaurant-service
  ports:
  - port: 5004
    targetPort: 5004
  type: ClusterIP 