apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: cravecart
  
  
  labels:
    app: restaurant-service
  annotations:
    cloud.google.com/load-balancer-ip: "34.133.20.229"
spec:
  type: LoadBalancer
  loadBalancerIP: "34.133.20.229"
  selector:
    app: restaurant-service
  ports:
  - port: 5004
    targetPort: 5004
    name: http
