apiVersion: v1
kind: Service
metadata:
  name: restaurant-service

  labels:
    app: restaurant-service
  annotations:
    cloud.google.com/load-balancer-ip: "34.111.17.63"
spec:
  selector:
    app: restaurant-service
  ports:
  - port: 5004
    targetPort: 5004
    name: http
