apiVersion: v1
kind: Service
metadata:
  name: user-service

  labels:
    app: user-service
  annotations:
    cloud.google.com/load-balancer-ip: "34.8.57.185"
spec:
  selector:
    app: user-service
  ports:
  - port: 3001
    targetPort: 3001
    name: http
