apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: cravecart
 
  labels:
    app: user-service
  annotations:
    cloud.google.com/load-balancer-ip: "34.132.7.64"
spec:
  type: LoadBalancer
  loadBalancerIP: "34.132.7.64"
  selector:
    app: user-service
  ports:
  - port: 3001
    targetPort: 3001
    name: http
